#pragma kernel Blur

Texture2D<float4> _Source;
RWTexture2D<float4> _Result;

float2 _Size;
int _Radius;

[numthreads(32, 32, 1)]
void Blur(uint3 id : SV_DispatchThreadID)
{
    [branch] if (id.x >= _Size.x || id.y >= _Size.y) return;

    float4 result = 0;
    float count = 0;

    for (int x = -_Radius; x <= _Radius; x++)
    {
        for (int y = -_Radius; y <= _Radius; y++)
        {
            const int2 uv = id.xy + int2(x, y);
            
            if (uv.x < 0 || uv.y < 0 || uv.x >= _Size.x || uv.y >= _Size.y)
                continue;

            result += _Source[uv];
            count++;
        }
    }

    _Result[id.xy] = result * rcp(count);
}